name = "dcc-os-api"
main = "./worker.js"
compatibility_date = "2026-07-17"
workers_dev = true

[site]
bucket = "."
include = ["index.html", "app.js", "styles.css", "manifest.webmanifest", "sw.js", "assets/**/*", "icon-*.png"]
